#!/bin/bash

####################################################
# CREATION     : 2016-07-04
# MODIFICATION : 2016-10-26

# I3block's blocklet which:
# - Show current temperature
# - Show temperature for the next 3 days with a left click
# - Update temperature with a middle click

# Requirements:
# - curl
# - yad (For mouse interaction)
#
####################################################
curl "https://wttr.in/Sheffield?format=+%c%t"

